Feature/admin login ui
pham28122013/shopbanhang pull request #21
Opened 2019-10-16 07:06 UTC by pham28122013

2019-11-20 06:29 UTC, pham28122013 commented
![login](https://user-images.githubusercontent.com/39374984/69214534-cae30980-0b99-11ea-8b15-c5a7342ef635.png)

2019-11-20 09:07 UTC, splendidspecial requested changes
Please fix my comment

2019-11-20 09:07 UTC, splendidspecial commented on app/Http/Controllers/Auth/LoginController.php
> +use Illuminate\Support\Facades\Auth;
`Facade` thì `use Auth;` là đủ rồi, lỗi này e bị lặp lại

2019-11-20 09:07 UTC, splendidspecial commented on app/Http/Controllers/Auth/LoginController.php
> +        if(Auth::attempt($this->userService->login($request)))
ko cần gọi service ở đây, viết như bình thường và thêm điều kiện `is_active = 1`

2019-11-20 09:07 UTC, splendidspecial commented on app/Http/Kernel.php
> +        'login' =>\App\Http\Middleware\login::class,
Sửa thành `'admin' =>\App\Http\Middleware\IsAdmin::class,`

2019-11-20 09:07 UTC, splendidspecial commented on app/Http/Middleware/login.php
> +        if (Auth::check()) {
Chổ này viết dài dòng quá, chỉ cần viết, nếu user đã login có role_id là 1 hoặc 2 thì `return $next($request);`, còn k thì cho về trang chủ

2019-11-20 09:07 UTC, splendidspecial commented on app/Models/User.php
> +    const ADMIN = 1;
hằng `ROLE` đã định nghĩa rõ ràng rồi, sao lại thêm hằng `ADMIN` e

2019-11-20 09:07 UTC, splendidspecial commented on routes/web.php
> +Route::namespace('Backend')->middleware('login')->group(function(){
dùng 2 middleware là 'auth' và `admin`

2019-11-20 09:07 UTC, splendidspecial commented on app/Http/Controllers/Auth/LoginController.php
> +        $this->userService->logout();
ko cần gọi service ở đây, viết thẳng ra luôn

2019-11-21 08:39 UTC, splendidspecial requested changes
Please fix my comment

2019-11-21 08:39 UTC, splendidspecial commented on app/Http/Controllers/Auth/LoginController.php
> +    private $userService;
xóa đi e

2019-11-21 08:39 UTC, splendidspecial commented on app/Http/Controllers/Auth/LoginController.php
> +        if(Auth::attempt(['email' => $email,'password' => $password]))
thêm is_active vào mảng, ko cần if phía dưới

2019-11-21 08:39 UTC, splendidspecial commented on app/Http/Middleware/IsAdmin.php
> +        if (Auth::check()) {
`role_id == User::ACTIVE` !?

2019-11-21 08:39 UTC, splendidspecial commented on app/Http/Controllers/Auth/LoginController.php
> +        if(Auth::attempt(['email' => $email,'password' => $password, 'is_active' => User::ACTIVE], $request->has('remember'))) {
$remember = $request->has('remember')

2019-11-21 09:05 UTC, splendidspecial approved these changes
LGTM

2019-11-21 09:06 UTC, merged