feature/admin_listUsers
pham28122013/shopbanhang pull request #27
Opened 2019-11-06 10:02 UTC by pham28122013

![listusers](https://user-images.githubusercontent.com/39374984/68288593-42ec0280-00b7-11ea-9ce7-5708bbc4a03e.png)

2019-11-06 10:29 UTC, splendidspecial requested changes
Please fix my comment

2019-11-06 10:29 UTC, splendidspecial commented on app/Http/Controllers/Backend/UserController.php
> +    public function create()
hàm này chưa dùng, xóa đi e

2019-11-06 10:29 UTC, splendidspecial commented on app/Http/Controllers/Backend/UserController.php
> +    public function store(Request $request)
hàm này chưa dùng, xóa đi e

2019-11-06 10:29 UTC, splendidspecial commented on app/Http/Controllers/Backend/UserController.php
> +    public function edit($id)
hàm này chưa dùng, xóa đi e

2019-11-06 10:29 UTC, splendidspecial commented on app/Http/Controllers/Backend/UserController.php
> +    public function update(Request $request, $id)
hàm này chưa dùng, xóa đi e

2019-11-06 10:29 UTC, splendidspecial commented on app/Http/Controllers/Backend/UserController.php
> +    public function destroy($id)
hàm này chưa dùng, xóa đi e

2019-11-06 10:29 UTC, splendidspecial commented on routes/web.php
> +    Route::resource('users', 'UserController');
chỉ dùng hàm `index()` thì khai báo only index thôi

2019-11-06 10:29 UTC, splendidspecial commented on resources/views/admin/users/list.blade.php
> +                    <tr class="text-center">
cho thẻ <tr> thuộc vào trong cho dễ nhìn, giống thẻ `thead tr` phía trên

2019-11-06 10:29 UTC, splendidspecial commented on resources/views/admin/users/list.blade.php
> +                        <td>{{$user->is_active}}</td>
Hiện chữ ra tương ứng với giá trị:
0 => Inactive (làm thẻ màu đỏ)
1 => Inactive (làm thẻ màu xanh lá cây)

2019-11-06 10:29 UTC, splendidspecial commented on app/Http/Controllers/Backend/UserController.php
> +        $users = User::paginate(10);
Controller sẽ làm việc với `Services`, Services sẽ làm việc với Model
Controller => Services => Models.
Ví dụ tạo UserService.php trong thư mục Services, rồi viết hàm `getAllUsers()` để lấy dữ liệu

2019-11-06 10:29 UTC, splendidspecial commented on app/Http/Controllers/Backend/UserController.php
> +use App\User;
đổi `App\User` => `App\Models\User`

2019-11-07 06:08 UTC, pham28122013 commented
![list-user](https://user-images.githubusercontent.com/39374984/68364141-afbad780-015f-11ea-8344-0a2aca51d788.png)

2019-11-07 06:34 UTC, splendidspecial requested changes
Cập nhật lại hình ảnh mới cho a nhé

2019-11-07 06:34 UTC, splendidspecial commented on app/Http/Controllers/Backend/UserController.php
> +use Illuminate\Http\Request;
chưa dùng thì xóa đi e

2019-11-07 06:34 UTC, splendidspecial commented on app/Http/Controllers/Backend/UserController.php
> +     *
bổ sung description

2019-11-07 06:34 UTC, splendidspecial commented on app/Services/Backend/UserService.php
> +        return User::paginate(10);
ko viết hardcode
định nghĩa `const ITEMS_PER_PAGE = 10` ở model User rồi gọi vào UserService

2019-11-07 06:34 UTC, splendidspecial commented on resources/views/admin/users/list.blade.php
> +            </div>
paginate ở UI nằm chỗ nào !?

2019-11-07 06:34 UTC, splendidspecial commented on resources/views/admin/users/list.blade.php
> +                                    if ($user->is_active == 0) {
ko viết hardcode, đinh nghĩa số 0 vào model User rồi gọi ra

2019-11-07 06:34 UTC, splendidspecial commented on resources/views/admin/users/list.blade.php
> +                            <td>{{$user->role_id}}</td>
Tương tự như `Status`. Hiện role tương ứng với role_id
1 => Admin
2 => Sub admin
3 => User

2019-11-07 06:34 UTC, splendidspecial commented on resources/views/admin/users/list.blade.php
> +                                <input type="hidden" name="_method" value="delete" /> {{csrf_field()}}
cho `csrf_field` xuống dòng

2019-11-07 06:34 UTC, splendidspecial commented on resources/views/admin/users/list.blade.php
> +                            <th>Tên</th>
Em nên viết thống nhất 1 ngôn ngữ thôi. Kiểm tra lại nhé

2019-11-08 06:13 UTC, pham28122013 commented
![user-index](https://user-images.githubusercontent.com/39374984/68453910-82d2f700-0229-11ea-83c4-d37c975c61f1.png)

2019-11-08 06:24 UTC, splendidspecial requested changes
Xóa hết hình đi, để hình mới nhất chỗ description thôi e

2019-11-08 06:24 UTC, splendidspecial commented on app/Models/User.php
> +    const ROLE_ID = [ 'ADMIN' => 1 , 'SUP_ADMIN' => 2, 'USER' => 3];
`ROLE_ID` => `ROLE`
`SUP_ADMIN` => `SUB_ADMIN`

2019-11-08 06:24 UTC, splendidspecial commented on resources/views/admin/users/list.blade.php
> +                    <h1 class="page-header">Danh sách
Đổi qua tiếng anh luôn đi e

2019-11-08 06:24 UTC, splendidspecial commented on resources/views/admin/users/list.blade.php
> +                            <th>Role_id</th>
`Role_id` => `Role`

2019-11-08 06:24 UTC, splendidspecial commented on resources/views/admin/users/list.blade.php
> +                                    if ($user->role_id == App\Models\User::ROLE_ID['ADMIN'] ) {
dùng @if @elseif @else @endif của laravel e

2019-11-08 06:24 UTC, splendidspecial commented on resources/views/admin/users/list.blade.php
> +                                    if ($user->is_active == App\Models\User::INACTIVE ) {
dùng @if

2019-11-08 06:41 UTC, pham28122013 commented
![user-index](https://user-images.githubusercontent.com/39374984/68455218-63d66400-022d-11ea-9701-2d1287f59570.png)

2019-11-08 06:59 UTC, splendidspecial requested changes
Please check my comment

2019-11-08 06:59 UTC, splendidspecial commented on app/Models/User.php
> +    const ITEMS_PER_PAGE = 10;
mỗi cái cách 1 dòng cho dễ nhìn e, viết sát quá khó nhìn

2019-11-08 06:59 UTC, splendidspecial commented on app/Services/Backend/UserService.php
> +
xóa dòng này đi e

2019-11-08 06:59 UTC, splendidspecial commented on app/Services/Backend/UserService.php
> +
xóa 2 dòng này đi e

2019-11-08 06:59 UTC, splendidspecial commented on resources/views/admin/users/list.blade.php
> +                                    <button class="btn btn-sm btn-success   rounded-0">Sup Admin</button>
Sub Admin

2019-11-08 07:07 UTC, splendidspecial approved these changes
LGTM

2019-11-08 07:08 UTC, merged